### ISSUE TITLE
Access denied when pulling image

### ISSUE THREAD

**Issue by Ivarz** [GenomicDataInfrastructure/starter-kit-lsaai-mock#8]
Hi! 
I'm experiencing an access issue when pulling lsaai-mock container:
![image](https://github.com/user-attachments/assets/17e090e8-347c-4029-9a41-e2a86b5564c1)

Problem was encountered on Rocky linux 9 and replicated on a fresh fedora 40 installation.
Previously it worked fine.

Thanks!

**Comment by AlexCork1** [comment]
Hi!

Did you try `docker login` first? That is usually the cause for this kind of problem.

**Comment by mrtamm** [comment]
I am facing the same problem. The Docker registry is not public and I don't have login credentials to download the `registry.gitlab.ics.muni.cz:443/perun-proxy-aai/containers/docker-gdi` image.

**Comment by AlexCork1** [comment]
I used the following steps:
1. create an account https://hub.docker.com/
2. in terminal you use to run docker compose, first execute command `docker login` and insert log in information defined in 1. step
3. run docker compose like you did. This worked for me.
4. if this is not working try restarting docker service (docker desktop on windows for example) and repeat steps 2 and 3

**Comment by Ivarz** [comment]
No luck for me:
![image](https://github.com/user-attachments/assets/899d2738-f8fc-4675-a3f3-bb6fe34b0b60)

**Comment by mrtamm** [comment]
@Ivarz You need to change the Docker image name to
`registry.gitlab.ics.muni.cz:443/perun/deployment/proxyidp/proxyidp-public-docker-images/ls_aai_mock:2.5.2-broker2.1.10-tomcat9.0-jdk11`

(Actually the port number is the default, so this also works:
`registry.gitlab.ics.muni.cz/perun/deployment/proxyidp/proxyidp-public-docker-images/ls_aai_mock:2.5.2-broker2.1.10-tomcat9.0-jdk11`)

You probably have an old version of the docker-compose.yml file. The name was changed [here](https://github.com/GenomicDataInfrastructure/starter-kit-lsaai-mock/commit/32c4efdd4100fa60823463667181ae114a41d33e)

(My issue is now resolved.)

**Comment by Ivarz** [comment]
@mrtamm indeed, this works. Thanks, it resolved my issue too!
